"""MACD + RSI + EMA strategy — universe + time-bucketed analytics.

Mirrors ``7_Vwap_Ema_Volume.py``. The strategy is the momentum-confirmation
setup that fires only in the first 90 minutes after the cash session open:

  - LONG: MACD histogram flips positive + RSI crosses above 50 + close above
    EMA(20), with RSI < 75 to avoid overbought fades.
  - SHORT: mirror image, RSI > 25 floor.
  - EXIT: MACD histogram crossover reversal.

Tabs:
  - Summary: per-symbol KPIs + top/bottom 20 by total return.
  - By hour of day: WR / trades / net P&L per 5-min IST slot.
  - By day of week: same buckets + heatmap.
  - Drilldown: live retunable backtest for one symbol.

Universe artefacts (written by ``scripts/run_macd_rsi_ema_universe.py``):
  - results/sweep_macd_rsi_ema_universe.csv
  - results/macd_rsi_ema_universe_trades.parquet
"""
from __future__ import annotations

from pathlib import Path
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from strategies import MacdRsiEma, REGISTRY, run_backtest, run_sweep
from strategies import data as strat_data

IST = ZoneInfo("Asia/Kolkata")
UNIVERSE_TRADES = Path("results/macd_rsi_ema_universe_trades.parquet")
UNIVERSE_SUMMARY = Path("results/sweep_macd_rsi_ema_universe.csv")

st.set_page_config(
    page_title="MACD+RSI+EMA · Stock Alert Bot",
    page_icon="🔥",
    layout="wide",
)
st.title("🔥 MACD + RSI + EMA")
st.caption(
    "Momentum-confirmation triple-gate. **Long** = MACD histogram flips "
    "positive + RSI crosses above 50 + close > EMA(20), with RSI < 75 to "
    "avoid overbought fades. **Short** = mirror image, RSI > 25 floor. "
    "**Exit** = MACD histogram crossover reversal. **Entries only fire in "
    "the first 90 minutes after the session open** (09:15-10:45 IST)."
)

# ---------------------------------------------------------------------------
# Sidebar — drilldown params
# ---------------------------------------------------------------------------

with st.sidebar:
    st.header("Drilldown params")
    st.caption(
        "Universe parquet is generated by "
        "`scripts/run_macd_rsi_ema_universe.py` with **default** params. "
        "These sliders only retune the live drilldown tab."
    )
    macd_fast = st.number_input("MACD fast", min_value=2, max_value=50, value=12)
    macd_slow = st.number_input("MACD slow", min_value=3, max_value=200, value=26)
    macd_signal = st.number_input(
        "MACD signal", min_value=2, max_value=50, value=9,
    )
    rsi_period = st.number_input(
        "RSI period", min_value=2, max_value=100, value=14,
    )
    rsi_mid = st.slider("RSI midline", 30.0, 70.0, 50.0, step=1.0)
    rsi_low = st.slider("RSI floor (avoid below)", 5.0, 49.0, 25.0, step=1.0)
    rsi_high = st.slider("RSI ceiling (avoid above)", 51.0, 95.0, 75.0, step=1.0)
    ema_period = st.number_input(
        "EMA period", min_value=2, max_value=200, value=20,
    )
    minutes_after_open = st.slider(
        "Entry window (min after open)", 15, 300, 90, step=15,
    )
    st.divider()
    st.header("Backtest knobs")
    equity = st.number_input(
        "Starting equity (₹)", min_value=10_000, value=100_000, step=10_000,
    )
    qty_pct = st.slider("Qty as % of equity", 0.01, 1.0, 0.10, step=0.01)
    max_loss = st.slider(
        "Max intraday loss % (kill switch)", 0.1, 5.0, 1.0, step=0.1,
    )
    apply_costs = st.checkbox("Apply round-trip costs", value=True)

if macd_slow <= macd_fast:
    st.error("MACD slow must be greater than MACD fast.")
    st.stop()
if not (rsi_low < rsi_mid < rsi_high):
    st.error("Need RSI floor < midline < ceiling.")
    st.stop()

# ---------------------------------------------------------------------------
# Load universe artefacts
# ---------------------------------------------------------------------------


@st.cache_data(ttl=60, show_spinner=False)
def _load_universe_trades() -> pd.DataFrame | None:
    if not UNIVERSE_TRADES.exists():
        return None
    df = pd.read_parquet(UNIVERSE_TRADES)
    if "entry_ts" in df.columns and not pd.api.types.is_datetime64_any_dtype(
        df["entry_ts"]
    ):
        df["entry_ts"] = pd.to_datetime(df["entry_ts"], utc=True)
    if df["entry_ts"].dt.tz is None:
        df["entry_ts"] = df["entry_ts"].dt.tz_localize("UTC")
    df["entry_ts_ist"] = df["entry_ts"].dt.tz_convert(IST)
    df["hour_slot"] = df["entry_ts_ist"].dt.strftime("%H:%M")
    df["hour"] = df["entry_ts_ist"].dt.hour
    df["dow"] = df["entry_ts_ist"].dt.day_name()
    df["is_win"] = (df["pnl_net"] > 0).astype(int)
    return df


@st.cache_data(ttl=60, show_spinner=False)
def _load_universe_summary() -> pd.DataFrame | None:
    if not UNIVERSE_SUMMARY.exists():
        return None
    return pd.read_csv(UNIVERSE_SUMMARY)


uni_trades = _load_universe_trades()
uni_summary = _load_universe_summary()

cache = strat_data.cache_summary("5m", 60)
if cache.empty:
    st.warning(
        "No 5m / 60d cache yet. Populate with:\n\n"
        "```\npython scripts/run_macd_rsi_ema_universe.py\n```"
    )
    st.stop()
cached_symbols = sorted(cache["symbol"].tolist())

# ---------------------------------------------------------------------------
# Top KPIs
# ---------------------------------------------------------------------------

if uni_trades is not None and uni_summary is not None and not uni_summary.empty:
    total_trades = int(uni_summary["trades"].sum())
    total_wins = int(uni_summary["wins"].sum())
    weighted_wr = (total_wins / total_trades * 100.0) if total_trades else 0.0
    avg_return = float(uni_summary["total_return_pct"].mean())
    profitable = int((uni_summary["total_return_pct"] > 0).sum())
    source_label = (
        f"Universe sweep · {len(uni_summary)} symbols · "
        f"`{UNIVERSE_TRADES.name}`"
    )
else:
    @st.cache_data(ttl=300, show_spinner="Running mini sweep (cached symbols)...")
    def _mini_sweep(symbols: tuple[str, ...]) -> pd.DataFrame:
        return run_sweep(
            [("macd_rsi_ema", {})], list(symbols),
            interval="5m", days=60, refresh=False,
        )

    mini = _mini_sweep(tuple(cached_symbols))
    total_trades = int(mini["trades"].sum()) if not mini.empty else 0
    total_wins = int(mini["wins"].sum()) if not mini.empty else 0
    weighted_wr = (total_wins / total_trades * 100.0) if total_trades else 0.0
    avg_return = float(mini["total_return_pct"].mean()) if not mini.empty else 0.0
    profitable = (
        int((mini["total_return_pct"] > 0).sum()) if not mini.empty else 0
    )
    source_label = (
        f"Cache-only mini sweep · {len(cached_symbols)} symbols. Run "
        "`python scripts/run_macd_rsi_ema_universe.py` for the full "
        "NIFTY 500 view."
    )
    uni_summary = mini

st.caption(source_label)
k1, k2, k3, k4, k5 = st.columns(5)
k1.metric("Symbols", f"{len(uni_summary)}")
k2.metric("Total trades", f"{total_trades:,}")
k3.metric("Win rate (trade-weighted)", f"{weighted_wr:.1f}%")
k4.metric("Avg return / symbol", f"{avg_return:+.2f}%")
k5.metric("Profitable symbols", f"{profitable} / {len(uni_summary)}")
st.divider()

# ---------------------------------------------------------------------------
# Tabs
# ---------------------------------------------------------------------------

tab_summary, tab_hour, tab_dow, tab_drill = st.tabs(
    ["📋 Summary", "🕐 By hour of day", "📅 By day of week", "🔬 Symbol drilldown"]
)


def _wr_table(
    trades: pd.DataFrame, group_col: str, order: list | None = None,
) -> pd.DataFrame:
    g = trades.groupby(group_col).agg(
        trades=("pnl_net", "count"),
        wins=("is_win", "sum"),
        net_pnl=("pnl_net", "sum"),
        avg_pnl=("pnl_net", "mean"),
    )
    g["win_rate_pct"] = (g["wins"] / g["trades"] * 100.0).round(1)
    g["net_pnl"] = g["net_pnl"].round(0)
    g["avg_pnl"] = g["avg_pnl"].round(1)
    g = g[["trades", "wins", "win_rate_pct", "net_pnl", "avg_pnl"]]
    if order is not None:
        g = g.reindex(order).fillna(0)
    return g.reset_index()


def _wr_bar_chart(df: pd.DataFrame, group_col: str, title: str) -> go.Figure:
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=df[group_col], y=df["win_rate_pct"],
        marker_color=[
            "#26a69a" if v >= 50 else "#ef5350" for v in df["win_rate_pct"]
        ],
        name="Win rate %",
    ))
    fig.add_trace(go.Scatter(
        x=df[group_col], y=df["trades"], name="Trades",
        line=dict(color="#fdd835", width=2), yaxis="y2",
    ))
    fig.add_hline(y=50.0, line=dict(color="#888888", dash="dot", width=1))
    fig.update_layout(
        template="plotly_dark", height=380, title=title,
        margin=dict(l=10, r=10, t=40, b=10),
        yaxis=dict(title="Win rate %", range=[0, 100]),
        yaxis2=dict(title="Trades", overlaying="y", side="right",
                    showgrid=False),
        legend=dict(orientation="h", yanchor="top", y=1.10,
                    xanchor="left", x=0),
    )
    return fig


# ---- Tab 1 — Summary ------------------------------------------------------

with tab_summary:
    st.subheader("Per-symbol results")
    summary_show = uni_summary.copy()
    for col in ("win_rate_pct", "total_return_pct", "max_dd_pct"):
        if col in summary_show.columns:
            summary_show[col] = summary_show[col].round(2)
    if "ending_equity" in summary_show.columns:
        summary_show["ending_equity"] = summary_show["ending_equity"].round(0)
    summary_show = summary_show.sort_values(
        "total_return_pct", ascending=False,
    ).reset_index(drop=True)
    st.dataframe(
        summary_show, width="stretch",
        height=min(640, 40 + 36 * len(summary_show)),
    )

    cc1, cc2 = st.columns(2)
    with cc1:
        top = summary_show.head(20)
        fig = go.Figure(go.Bar(
            x=top["total_return_pct"], y=top["symbol"], orientation="h",
            marker_color="#26a69a",
        ))
        fig.update_layout(
            template="plotly_dark", height=520, title="Top 20 by total return %",
            margin=dict(l=10, r=10, t=40, b=10),
            xaxis_title="Total return %", yaxis_title="",
            yaxis=dict(autorange="reversed"),
        )
        st.plotly_chart(fig, width="stretch")
    with cc2:
        worst = summary_show.tail(20).iloc[::-1]
        fig = go.Figure(go.Bar(
            x=worst["total_return_pct"], y=worst["symbol"], orientation="h",
            marker_color="#ef5350",
        ))
        fig.update_layout(
            template="plotly_dark", height=520,
            title="Bottom 20 by total return %",
            margin=dict(l=10, r=10, t=40, b=10),
            xaxis_title="Total return %", yaxis_title="",
            yaxis=dict(autorange="reversed"),
        )
        st.plotly_chart(fig, width="stretch")


# ---- Tab 2 — By hour of day ----------------------------------------------

with tab_hour:
    if uni_trades is None:
        st.info(
            "Run `python scripts/run_macd_rsi_ema_universe.py` to populate "
            f"`{UNIVERSE_TRADES}` and unlock hour-of-day analytics."
        )
    elif uni_trades.empty:
        st.info("No trades in the universe parquet.")
    else:
        st.subheader("Overall — every entry across every symbol")
        slot_order = sorted(uni_trades["hour_slot"].unique())
        overall = _wr_table(uni_trades, "hour_slot", order=slot_order)
        st.plotly_chart(
            _wr_bar_chart(overall, "hour_slot",
                          "Win rate by entry slot (overall)"),
            width="stretch",
        )
        st.dataframe(overall, width="stretch",
                     height=min(440, 40 + 36 * len(overall)))

        st.divider()
        st.subheader("Per symbol — pick one")
        sym_options = sorted(uni_trades["symbol"].unique())
        sym = st.selectbox(
            "Symbol", sym_options, key="hour_sym",
            index=0,
        )
        sym_df = uni_trades[uni_trades["symbol"] == sym]
        if sym_df.empty:
            st.info(f"No trades for {sym}.")
        else:
            sym_slot_order = sorted(sym_df["hour_slot"].unique())
            per = _wr_table(sym_df, "hour_slot", order=sym_slot_order)
            st.plotly_chart(
                _wr_bar_chart(per, "hour_slot",
                              f"Win rate by entry slot — {sym}"),
                width="stretch",
            )
            st.dataframe(per, width="stretch",
                         height=min(440, 40 + 36 * len(per)))


# ---- Tab 3 — By day of week ----------------------------------------------

DOW_ORDER = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]


with tab_dow:
    if uni_trades is None:
        st.info(
            "Run `python scripts/run_macd_rsi_ema_universe.py` to populate "
            f"`{UNIVERSE_TRADES}` and unlock day-of-week analytics."
        )
    elif uni_trades.empty:
        st.info("No trades in the universe parquet.")
    else:
        st.subheader("Overall — every entry across every symbol")
        overall_d = _wr_table(uni_trades, "dow", order=DOW_ORDER)
        st.plotly_chart(
            _wr_bar_chart(overall_d, "dow",
                          "Win rate by day of week (overall)"),
            width="stretch",
        )
        st.dataframe(overall_d, width="stretch",
                     height=min(260, 40 + 36 * len(overall_d)))

        st.divider()
        st.subheader("Per symbol")
        sym_options = sorted(uni_trades["symbol"].unique())
        sym = st.selectbox("Symbol", sym_options, key="dow_sym", index=0)
        sym_df = uni_trades[uni_trades["symbol"] == sym]
        if sym_df.empty:
            st.info(f"No trades for {sym}.")
        else:
            per = _wr_table(sym_df, "dow", order=DOW_ORDER)
            st.plotly_chart(
                _wr_bar_chart(per, "dow", f"Win rate by day of week — {sym}"),
                width="stretch",
            )
            st.dataframe(per, width="stretch",
                         height=min(260, 40 + 36 * len(per)))

        st.divider()
        st.subheader("Heatmap — hour-of-day × day-of-week (overall WR%)")
        pivot = uni_trades.pivot_table(
            index="dow", columns="hour_slot",
            values="is_win", aggfunc="mean",
        )
        pivot = (pivot * 100.0).round(1).reindex(DOW_ORDER)
        fig_h = go.Figure(data=go.Heatmap(
            z=pivot.values, x=list(pivot.columns), y=list(pivot.index),
            colorscale=[(0.0, "#b71c1c"), (0.5, "#1a1d24"), (1.0, "#1b5e20")],
            zmid=50.0, colorbar=dict(title="WR %"),
            hovertemplate="%{y} %{x}: %{z:.1f}%<extra></extra>",
        ))
        fig_h.update_layout(
            template="plotly_dark", height=320,
            margin=dict(l=10, r=10, t=10, b=10),
            xaxis_title="Entry slot (IST)", yaxis_title="",
        )
        st.plotly_chart(fig_h, width="stretch")


# ---- Tab 4 — Symbol drilldown --------------------------------------------

with tab_drill:
    st.subheader("Live drilldown — sidebar params apply here")
    drill_universe = sorted(set(cached_symbols))
    pick = st.selectbox(
        "Pick a symbol", options=drill_universe, index=0, key="drill_sym",
    )

    try:
        df_bars = strat_data.load(pick, interval="5m", days=60, refresh=False)
    except KeyError as e:
        st.error(str(e))
        st.stop()

    params = dict(
        macd_fast=int(macd_fast), macd_slow=int(macd_slow),
        macd_signal=int(macd_signal),
        rsi_period=int(rsi_period), rsi_mid=float(rsi_mid),
        rsi_low=float(rsi_low), rsi_high=float(rsi_high),
        ema_period=int(ema_period),
        minutes_after_open=int(minutes_after_open),
    )
    strat = MacdRsiEma(**params)
    r = run_backtest(
        strat, df_bars,
        starting_equity=float(equity), qty_pct=float(qty_pct),
        max_intraday_loss_pct=float(max_loss), apply_costs=bool(apply_costs),
    )

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Trades", f"{r.num_trades}")
    c2.metric("Win rate", f"{r.win_rate_pct:.1f}%")
    c3.metric("Total return", f"{r.total_return_pct:+.2f}%")
    c4.metric("Max drawdown", f"{r.max_drawdown_pct:.2f}%")

    if not r.equity_curve.empty:
        fig_eq = go.Figure(go.Scatter(
            x=r.equity_curve.index, y=r.equity_curve.values,
            line=dict(color="#26a69a", width=2), name="Equity",
        ))
        fig_eq.add_hline(
            y=float(equity), line=dict(color="#888888", dash="dot", width=1),
        )
        fig_eq.update_layout(
            template="plotly_dark", height=320,
            margin=dict(l=10, r=10, t=10, b=10),
            yaxis_title="Equity (₹)", xaxis_title="",
        )
        st.plotly_chart(fig_eq, width="stretch")

    tdf = r.trades_df()
    if tdf.empty:
        st.info("No trades on this symbol with the current params.")
    else:
        tdf_show = tdf.copy()
        for col in ("entry_price", "exit_price", "pnl_gross", "pnl_net"):
            if col in tdf_show.columns:
                tdf_show[col] = tdf_show[col].round(2)
        if "return_pct" in tdf_show.columns:
            tdf_show["return_pct"] = tdf_show["return_pct"].round(3)
        st.markdown(f"**Trades — {pick}**")
        st.dataframe(
            tdf_show, width="stretch",
            height=min(420, 40 + 36 * len(tdf_show)),
        )

st.divider()
st.caption(
    "Universe sweep: `python scripts/run_macd_rsi_ema_universe.py` "
    "(writes `results/sweep_macd_rsi_ema_universe.csv` + "
    "`results/macd_rsi_ema_universe_trades.parquet`). "
    "Single symbol: `python -m strategies macd_rsi_ema --symbol RELIANCE.NS`."
)

assert "macd_rsi_ema" in REGISTRY, "macd_rsi_ema not in REGISTRY"
_ = np
